### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by carlosedp** [carlosedp/rebar3_diameter_compiler#14]
I'd love to have a couple of test cases to make sure the compiler is working.

Could you help out on this @RoadRunnr and @ebengt? I'm a little rusty on Erlang :)

**Comment by RoadRunnr** [comment]
I'm a bit of a loss of how a test for the plugin would work. I've checked a few of the other rebar3 plugins for inspiration, and almost none of them have tests.

**Comment by ebengt** [comment]
I have an idea about test, but that will have to wait until after work hours.

**Comment by ebengt** [comment]
I made a pull request with a test. #15

**Comment by carlosedp** [comment]
Fixed by #15
