### ISSUE TITLE
Problem with @name

### ISSUE THREAD

**Issue by dzimi** [carlosedp/rebar3_diameter_compiler#4]
Hi !
I think there is a problem with file name. 
I have some .dia files which has `@name` parameter inside. It defines the name of the generated dictionary module. Everything is fine when the `@name` value is the same as the file name, otherwise there is a problem during compilation. 

Case:
 File rfc4005_nas.dia : 

```
@name diameter_gen_rfc4005_nas
@inherits diameter_gen_base_rfc3588
```

File rfc4006_cc.dia: 

```
@name diameter_gen_rfc4006_cc
@inherits diameter_gen_base_rfc3588
@inherits diameter_gen_rfc4005_nas
```

It work only if this files names have `diameter_gen_` prefix. I think it worked with rebar v2.

**Comment by carlosedp** [comment]
The code that compiles the .dia files were a direct port of the rebar2 functionality. No changes were made other than creating the plugin wrapper for rebar3. Could you please test with rebar2 to assure this?

**Comment by carlosedp** [comment]
Actually, I tested with my app and added a @name property to a .dia file (without renaming the file).

After compiling, it generated the file with the name specified in the @name property so I think this is not an issue. Just confirm so I can close it.

**Comment by carlosedp** [comment]
Closing since I didn't have a confirmation of the problem and internal testing did not replicate the problem.
