### ISSUE TITLE
compilation fails; .beam files not generated in time?

### ISSUE THREAD

**Issue by laf0rge** [carlosedp/rebar3_diameter_compiler#8]
I've been playing with diameter dictionairies with lots of internal dependencies, and I'm having some troubles with the rebar3_diameter_compiler.  It actually resolves the dependencies and compiles a couple of .dia files to .erl/.hrl, but then when trying to compiler more of them, apparently it tries to compile .dia files without having the .beam files of the dependencies built.

In case you're interested, I've pushed the code to a temporary repository (even with typo in the name) at https://github.com/laf0rge/osmo_diamete2gsup

I'm not sure why it's not generating the .beam file before doing the next .dia -> erl/hrl translation.

If I compile the code manually, it works.

**Comment by carlosedp** [comment]
Can you test with latest version?
Thanks

**Comment by carlosedp** [comment]
Closing since no updates since then.
